### ISSUE TITLE
dosen't work with absolute path dependent

### ISSUE THREAD

**Issue by caikan** [thomas-darling/gulp-dependents#3]
The following Pug code with absolute path will not be parsed correctly:
`extends /layout.pug`

**Comment by thomas-darling** [comment]
This is does not look like something we support out of the box.
Are you using any custom `parserSteps` to parse this, and if so, can you post them?

**Comment by caikan** [comment]
Thank you. I have solved the problem with parserSteps function.
`var root = path.resolve(base)
var pugRule = {
	parserSteps: [
		/^\s*(?:extends|include)\s+(.+?)\s*$/gm,
		function(str) {
			var absolute = str.match(/^[\\/]+(.+)/);
			if (absolute) {
				str = path.resolve(root, absolute[1]);
			}
			return [str];
		}
	],
	postfixes: ['.pug', '.jade']
};
`
