### ISSUE TITLE
Support for @use and @forward rules

### ISSUE THREAD

**Issue by Ygnaaac** [thomas-darling/gulp-dependents#5]
Scss is going to deprecate `@import` rule. It's possible to add support for `@use` and `@forward` rules without passing additional config?

https://sass-lang.com/documentation/at-rules/import
> The Sass team discourages the continued use of the `@import` rule. Sass will gradually phase it out over the next few years, and eventually remove it from the language entirely. Prefer the `@use` rule instead.

**Comment by thomas-darling** [comment]
Absolutely!
I just published version 1.2.5 - try it out, and let me know if you encounter any issues :-)

**Comment by Ygnaaac** [comment]
Thank you, it works nicely :)
